### PR TITLE
Merge rust-lang/rust-bindgen v0.60.1 changes

### PR DESCRIPTION
**Pull request by chbaker0**

### CODE REVIEW

**Comment by chbaker0** [comment]
@adetaylor this passes all `autocxx` tests when I run locally

**Comment by adetaylor** [comment]
Thanks @chbaker0! These merges are a pain in the bum, so this is much appreciated.

**Comment by chbaker0** [comment]
Did you mean to merge this before https://github.com/google/autocxx/pull/1149

**Comment by adetaylor** [comment]
Ahem, yes.

**Pull request merged**
